### ISSUE TITLE
v0.2.6은 현재 정상 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by heumsi** [jckdotim/korean-grammar-action#21]
## 문제 현상

README에 나와있는 그대로 따라했으나, 다음과 같이 정상적으로 작동되지 않고 있습니다.

![image](https://user-images.githubusercontent.com/31306282/148261285-2fecd269-a827-43b4-b861-551ef4668e0f.png)

## 예상 원인

에러 메시지는 다음과 같았습니다.

```
Traceback (most recent call last):
  File "/fix.py", line 41, in <module>
    comment_fix_suggestion(
  File "/fix.py", line 29, in comment_fix_suggestion
    pr.create_comment(
  File "/usr/local/lib/python3.8/site-packages/github/PullRequest.py", line 387, in create_comment
    return self.create_review_comment(body, commit_id, path, position, side, line)
  File "/usr/local/lib/python3.8/site-packages/github/PullRequest.py", line 416, in create_review_comment
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequestReviewComment", "code": "invalid", "field": "pull_request_review_thread.path"}, {"resource": "PullRequestReviewComment", "code": "missing_field", "field": "pull_request_review_thread.diff_hunk"}], "documentation_url": "docs.github.com/rest"}
```

422 에러가 나는 걸로 보아, `create_comment`가 호출하는 REST API 엔드포인트에 변경사항이 있는 것 같습니다.

## 대안

이 프로젝트가 의존하는 PyGitHub가 업데이트 되지 않은지 꽤 된거 같습니다. 이를 최신으로 업데이트하면 최신의 GitHub REST API를 호출할거라 생각합니다.

곧 관련 PR 올려보겠습니다.

**Comment by heumsi** [comment]
수정 후 문제가 발생했던 레포에 액션을 v0.2.7 로 수정하고 해도 같은 현상이 발생하는군요.
위에 적은 예상 원인과 다른 문제일 수도 있겠네요... 

좀 더 트라이해본 뒤 다시 남겨보겠습니다.

**Comment by heumsi** [comment]
다른 레포에서 v0.2.6으로 해보니 잘 되는군요. 위에서 진행한 레포에서만 문제가 있던거 같습니다. 
이 이슈와 관련 PR은 닫겠습니다.
